inherit_gem:
  rubocop-gp:
    - ./config/default.yml

Gp/OptArgParameters:
  Enabled: false

Gp/ClassOrModuleDeclaredInWrongFile:
  Exclude:
    - lib/active_dry_deps/stub.rb

Gp/ModuleMethodInWrongFile:
  Exclude:
    - lib/active_dry_deps/stub.rb

AllCops:
  TargetRubyVersion: 3.0

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false
